### PR TITLE
Wip development

### PR DESCRIPTION
**Pull request by markedwardmurray**
@misterfifths walkthrough on how to set the simulated metric size. will begin the Segues & Nav Controllers unit

regarding https://github.com/learn-co-curriculum/mobile-development-with-ios-track/issues/24

please review by Thur 9/24

### CODE REVIEW

**Comment by markedwardmurray** [comment]
Reassigning to Joe since Tim is preparing for the new class.

**Comment by jmburges** [comment]
Needs a `.learn` file and good to go.

**Comment by jmburges** [comment]
Maybe also mention that by default we will do this on labs for them?

**Comment by jmburges** [comment]
:shipit:

**Comment by markedwardmurray** [comment]
will they need to know this when adding a new view controller to storyboard themselves?

**Comment by markedwardmurray** [comment]
has a `.learn`

**Pull request merged**
